### ISSUE TITLE
issue with predict.py

### ISSUE THREAD

**Issue by ahorvath** [wk989898/ARES-implement#7]
Hi, 

Having successfully installed the requeirments and run the training I tried to run the predict.py script as written in the readme file:

$ python3 predict.py  --model_path ARES.pt 
Traceback (most recent call last):
  File "/data/ARES-implement/predict.py", line 30, in <module>
    main(args)
  File "/data/ARES-implement/predict.py", line 19, in main
    out = net(V, atoms_info, atoms_lens)
  File "/ocal/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ARES-implement/model.py", line 38, in forward
    V = self.model1(V, atoms_info)
  File "/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ARES-implement/model.py", line 57, in forward
    V = self.interaction1(V)
  File "/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ARES-implement/model.py", line 170, in forward
    V[key] = (torch.einsum('acm,cd->amd',
  File "/local/lib/python3.10/site-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: einsum(): the number of subscripts in the equation (3) does not match the number of dimensions (4) for operand 0 and no ellipsis was given

Can you please help me with resolving this issue?

**Comment by wk989898** [comment]
You could modify `predict.py`: 
```
from batch_model import Net
```
Btw, this is a trial version, I recommend you to use the official code
